openapi: 3.0.0
info:
  title: Schedule API
  version: 1.0.0
  description: API documentation for Schedule application

tags:
  - name: Auth
    description: Auth API
  - name: ScheduleController
    description: 스케줄 관리 API
  - name: CommentController
    description: 댓글 API

paths:
  /api/auth/signup:
    post:
      summary: 회원가입
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                admin:
                  type: boolean
                adminToken:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: string
                example: "회원가입 성공"

  /api/auth/refresh:
    post:
      summary: 토큰 갱신
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/login:
    post:
      summary: 로그인
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/schedules/{id}:
    get:
      summary: 스케줄 상세 조회
      tags:
        - ScheduleController
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  assignee:
                    type: string
                  date:
                    type: string
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                        username:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                  file:
                    type: object
                    properties:
                      id:
                        type: integer
                      fileName:
                        type: string
                      fileExtension:
                        type: string
                      fileSize:
                        type: integer
                      createdDate:
                        type: string
                        format: date-time

    put:
      summary: 스케줄 수정
      tags:
        - ScheduleController
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object

    delete:
      summary: 스케줄 삭제
      tags:
        - ScheduleController
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: string
                example: "스케줄 삭제 성공"

  /api/schedules:
    get:
      summary: 스케줄 목록 조회
      tags:
        - ScheduleController
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    assignee:
                      type: string
                    date:
                      type: string

    post:
      summary: 스케줄 추가
      tags:
        - ScheduleController
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: 성공
          content:
            application/json:
              schema:
                type: object

  /api/schedules/validatePassword/{id}:
    post:
      summary: 비밀번호 검증
      tags:
        - ScheduleController
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: boolean

  /api/schedules/{scheduleId}/comments:
    post:
      summary: 댓글 작성
      tags:
        - CommentController
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  username:
                    type: string
                  createdAt:
                    type: string
                    format: date-time

  /api/comments/{commentId}:
    put:
      summary: 댓글 수정
      tags:
        - CommentController
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                  username:
                    type: string
                  createdAt:
                    type: string
                    format: date-time

    delete:
      summary: 댓글 삭제
      tags:
        - CommentController
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: string
                example: "댓글 삭제 성공"
